apiVersion: v1
kind: Service
metadata:
  name: golftv-static
  namespace: golftv
  labels:
    name: golftv-static
spec:
  type: NodePort
  selector:
    app: golftv-static
  ports:
    - name: http
      protocol: TCP
      nodePort: 30080
      port: 80
      targetPort: 80