apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: golftv-static
  namespace: golftv
  labels:
    name: golftv-static
    ver: '0.0.1'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golftv-static
  template:
    metadata:
      labels:
        app: golftv-static
        ver: '0.0.1'
    spec:
      containers:
      - name: golftv-static
        image: golftv-static:kubelocal
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80