apiVersion: v1
kind: Service
metadata:
  name: harperdb-client
  namespace: golftv
  labels:
    name: harperdb-client
spec:
  type: NodePort
  selector:
    app: harperdb-client
  ports:
    - name: http
      protocol: TCP
      nodePort: 30081
      port: 80
      targetPort: 8080